### ISSUE TITLE
Document how to run multiple scoring workers

### ISSUE THREAD

**Issue by ChandlerSwift** [UMDLARS/dtanm#47]
Either `docker stack deploy` with `replica`s, or `docker-compose up --scale worker=8`

https://stackoverflow.com/a/39663304/3814663

**Comment by ChandlerSwift** [comment]
Doing some reading, it seems like Docker seems to strongly recommend the `docker stack deploy` approach for production, though `docker-compose` is getting more production-worthy.

**Comment by ChandlerSwift** [comment]
docker-compose up --scale worker=8 was used successfully for the test run on 12/5/19

**Comment by pahp** [comment]
Could the number of worker threads be configurable from the admin panel?

**Comment by ChandlerSwift** [comment]
Technically? Yes, we could try to make that configurable from the admin panel. However, `docker-compose` (unlike Docker) doesn't have a nice python SDK so I'd have to reinvent several wheels to get there.

If you think there's high value in specifically having an admin panel control, you're welcome to re-open the issue. However, since it's just a slight modification the command being run when setting up the competition, it seems like this is a reasonable cost-benefit tradeoff.
