### ISSUE TITLE
Design an easy way for users to create attacks.

### ISSUE THREAD

**Issue by derpferd** [UMDLARS/dtanm#5]
With v2 attacks are packaged in a tarball with a predefined structure.
We would like a way for a user to easily create an attack.

Ideas:
- Have a website.
   - Users can enter command line arguments and stdin.
   - Users can upload files to be placed in the environment.
   - Users can download the attack tarball or directly submit it.
   - This site should allow different inputs based on which inputs the current challenge supports.
- Create a cli.
   - Users can create a directory with provided attack.
   - Utility can verify, package and submit attack.
   - If the current challenge only supports command line args: the cli could simply prompt the user for the args submit an attack.

**Comment by ChandlerSwift** [comment]
Done.
