### ISSUE TITLE
admin assign badges to teams

### ISSUE THREAD

**Issue by pahp** [UMDLARS/dtanm#96]
It would be cool if admins could assign badges to team, such as one for "You found a bug in gold!"

![image](https://user-images.githubusercontent.com/15266857/80769712-bb39fa80-8b13-11ea-8a91-fdcb8399402a.png)

**Comment by ChandlerSwift** [comment]
Displayed something like this? (Sorry, Julian :stuck_out_tongue_closed_eyes:)
![2020-05-03-204838_1900x708_scrot](https://user-images.githubusercontent.com/8261698/80931520-f9d3ed00-8d7f-11ea-8f7d-4880bc0b75fe.png)
