### ISSUE TITLE
Better about page

### ISSUE THREAD

**Issue by ChandlerSwift** [UMDLARS/dtanm#98]
Improve the `alert()` call in the menu with a proper bootstrap modal, and link to the contributors page on GitHub?

**Comment by jnowaczek** [comment]
Worth noting that the "About" link doesn't appear unless you're logged in. Is that the best place for it to go?

**Comment by ChandlerSwift** [comment]
A good point! I don't think it's important enough to deserve a spot in the main menu (left), nor on the home page, except maybe as a footer. Any ideas?

**Comment by ChandlerSwift** [comment]
Fixed by fc30ed7da2012db4cb53603dcdb2ae31f9367807
